version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-production-image
    container_name: my-production-container
    ports:
      - "80:80"  # Mapeia a porta 80 para a produção

